frk1: frk1.o
	@gcc frk1.c -o frk1

frk2: frk2.o
	@gcc frk2.c -o frk2

frk3: frk3.o
	@gcc frk3.c -o frk3

frk4: frk4.o
	@gcc frk4.c -o frk4

frk5: frk5.o
	@gcc frk5.c -o frk5

frk6: frk6.o
	@gcc frk6.c -o frk6

frk7: frk7.o
	@gcc frk7.c -o frk7

frk8: frk8.o
	@gcc frk8.c -o frk8

frk9: frk9.o
	@gcc frk9.c -o frk9

frk10: frk10.o
	@gcc frk10.c -o frk10

clean:
	@rm -rf a.out *.c~ *.o
